### ISSUE TITLE
chown doesn't do anything

### ISSUE THREAD

**Issue by katama77** [samjmck/ebay-monitor#3]
So is this program only for unix/lx?  I can install and run all commands, including chown in gitbash in Windows 10, but the file permissions never change no matter how many times I run it.  I tried chown +x and chown 755.  I guess this is because it doesn't work in NTFS?

**Comment by samjmck** [comment]
I have unfortunately only tested it on UNIX and Linux based systems, sorry. 

If you are using Windows, you might be better of trying to clone the repository and compiling an executable for your platform like that.

Slightly off-topic: it has been 2 years since I last tested this, it could be that the HTML structure of eBay's pages has since changed and that the tool doesn't work.

**Comment by katama77** [comment]
I'll give it a try, thanks

**Comment by JamesBlackhammer** [comment]
Hi, im a bit lost how do i get this onto my rasberry pi?
